--- # Seting up local server
- hosts: local
  user: deployer
  connection: local
  become: yes
  gather_facts: no
  pre_tasks:
  - name: Start time
    raw: date > /home/depolyer/time.log
  roles:
  - local
  post_tasks:
  - name: End Time
    raw: date >> /home/depolyer/time.log    
