--- # Seting up local server
- hosts: nginxserver
  users: deployer
  connection: ssh
  become: yes
  gather_facts: no
  pre_tasks:
  - name: Start time
    raw: date > /home/deployer/log/time.log
  roles:
  - nginxserver
  post_tasks:
  - name: End Time
    raw: date >> /home/deployer/log/time.log    
